--Q1. What is the total revenue generated by male vs female?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


--Q2.Which customers used a discount but still spent more than average purchase amount
SELECT customer_id,purchase_amount
FROM customer
WHERE purchase_amount >= (SELECT AVG(purchase_amount) FROM customer) AND discount_applied = 'Yes';


--Q3.Which are the top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating)::numeric,3) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping
SELECT shipping_type,ROUND(AVG(purchase_amount)::numeric,2) AS average_amount
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;


--Q5. Do subscribed customers spent more? Compare average spend and total revenue between subscribers and non-subscribers?
SELECT subscription_status,
   COUNT(customer_id) AS total_customers,
   SUM(purchase_amount) AS total_revenue,
   ROUND(AVG(purchase_amount)::numeric,5) AS average_spend
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;


--Q6.Which 5 products have the highest percentage of purchased with the discounts applied?
SELECT 
     item_purchased, 
	 COUNT(*) FILTER (WHERE discount_applied = 'Yes') AS dicount_count,
	 COUNT(*) AS total_count,
	 ROUND(
	      (COUNT(*) FILTER (WHERE discount_applied = 'Yes')::numeric / COUNT(*)::numeric)
	      * 100 , 2) AS dicount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY dicount_percentage DESC
LIMIT 5;


--Q7.Segment customers into new, returning,loyal based on their total number of previous purchases,
-- and show the count of each segment
SELECT segment, COUNT(*) as total_count FROM (
SELECT customer_id, SUM(previous_purchases) AS total_prev_purchases,
  CASE 
     WHEN SUM(previous_purchases) <= 10 THEN 'New'
	 WHEN SUM(previous_purchases) <= 30 THEN 'Returning'
	 ELSE 'Loyal'
  END AS segment
FROM customer
GROUP BY customer_id ) AS t
GROUP BY segment;

--Q8. What are the top 3 most purchased products within each category?
SELECT * FROM (
SELECT 
     category, 
	 item_purchased, 
	 COUNT(customer_id) AS total_orders,
	 ROW_NUMBER() OVER (
         PARTITION BY category
		 ORDER BY COUNT(customer_id) DESC
	 ) AS rank
FROM customer
GROUP BY item_purchased,category
ORDER BY category, total_orders DESC 
) AS t
WHERE rank <=3;


--Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
SELECT COUNT(customer_id) AS total_repeat_buyers,
COUNT(customer_id) FILTER (WHERE subscription_status = 'Yes') AS subs_repeat_buyers,
ROUND(
   (COUNT(customer_id) FILTER (WHERE subscription_status = 'Yes'))::numeric/ COUNT(customer_id)::numeric 
   * 100, 2) AS percentage_of_customers
FROM customer
WHERE previous_purchases > 5;


--Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

